MODELS: [MG, MF]
TREE: DataSimulated/trees/rootedtree.Primates.nhx
MUTATION_RATE_PER_GENERATION: 10.0
PROFILE: DataSimulated/preferences/np.prefs
EXON_SIZE: 498
NBR_EXON: 5
SEED: 42
ALPHA_ARRAY_LOG10_MIN: -0.69897
ALPHA_ARRAY_LOG10_MAX: 0.69897
ALPHA_ARRAY_STEPS: 3
LAMBDA_ARRAY_LOG10_MIN: -1
LAMBDA_ARRAY_LOG10_MAX: 1
LAMBDA_ARRAY_STEPS: 3
NUC_MATRIX: DataSimulated/matrices/nuc_matrix_Simiiformes.tsv
REPLICATES: 4