ALPHA_ARRAY_LOG10_MIN: -1
ALPHA_ARRAY_LOG10_MAX: 1
ALPHA_ARRAY_STEPS: 3
LAMBDA_ARRAY_LOG10_MIN: -1
LAMBDA_ARRAY_LOG10_MAX: 1
LAMBDA_ARRAY_STEPS: 3
TREE: DataSimulated/trees/rootedtree.Simiiformes.nhx
NUC_MATRIX: DataSimulated/matrices/nuc_matrix_Simiiformes.tsv
MUTATION_RATE_PER_GENERATION: 2.0
EXON_SIZE: 498
NBR_EXON: 15
SEED: 65489
MODELS: [MG, MF]
